import { Router } from "express";
import { userControllers } from "../controllers/user";
import { authToken } from "../libs/authToken";
const router = Router();
router.get("/", userControllers.index);
router.post("/createUser", userControllers.createUser);
router.put("/editUser/:id", userControllers.editUser);
router.delete("/deleteUser/:id", userControllers.deleteUser);
router.get("/getprofile/:id", authToken, userControllers.getProfile);
router.post("/logUser", userControllers.logUser);
export default router;